name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and analyze
    runs-on: self-hosted
    
    steps:
      # Checkout repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          set-safe-directory: false

      # Debug paths and temp directories
      - name: Debug Runner Paths
        run: |
          echo "RUNNER_TEMP: $RUNNER_TEMP"
          echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
          ls "$RUNNER_TEMP"
        shell: bash

      # Run sanity checks
      - name: Run Sanity Checks
        run: |
          SCRIPT_PATH=$(cygpath -u "${GITHUB_ACTION_PATH}/sanity-checks.sh")
          echo "Executing script at $SCRIPT_PATH"
          bash "$SCRIPT_PATH"
        shell: bash

      # Run SonarQube scan
      - uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
